export { default as CasingHome } from "./CasingHome"
export { default as CpuColler } from "./CpuColler"
export { default as CpuHome } from "./CpuHome"
export { default as GpuHome } from "./GpuHome"
export { default as MotherBoard } from "./MotherBoard"
export { default as PowerSupplay } from "./PowerSupplay"
export { default as RamHome } from "./RamHome"
export { default as Storage } from "./Storage"